CREATE TABLE BEN_XE (
    MaBenXe VARCHAR(20) PRIMARY KEY,
    TenBenXe VARCHAR(100) NOT NULL,
    DiaChi TEXT
);

CREATE TABLE TAI_XE (
    MaTaiXe VARCHAR(10) PRIMARY KEY,
    TenTaiXe VARCHAR(100) NOT NULL,
    SoDienThoai VARCHAR(15),
    BangLai VARCHAR(50) DEFAULT 'Hạng E',
    TrangThai VARCHAR(50) DEFAULT 'Sẵn sàng' CHECK (TrangThai IN ('Sẵn sàng', 'Đang hoạt động', 'Nghỉ'))

);

CREATE TABLE HANH_KHACH (
    MaHanhKhach VARCHAR(10) PRIMARY KEY,
    TenHanhKhach VARCHAR(100) NOT NULL,
    SoDienThoai VARCHAR(15)
);

CREATE TABLE TUYEN_XE (
    MaTuyen VARCHAR(20) PRIMARY KEY,
    TenTuyen VARCHAR(100) NOT NULL,
    MaBXdau VARCHAR(20) REFERENCES BEN_XE(MaBenXe),
    MaBXcuoi VARCHAR(20) REFERENCES BEN_XE(MaBenXe),
    GiaVe DECIMAL(12, 2) CHECK (GiaVe > 0)
);

CREATE TABLE XE_BUS (
    MaXe VARCHAR(10) PRIMARY KEY,
    BienSo VARCHAR(20) UNIQUE NOT NULL,
    SoCho INTEGER CHECK (SoCho > 0),
    TrangThai VARCHAR(50) DEFAULT 'Sẵn sàng' CHECK (TrangThai IN ('Sẵn sàng', 'Đang hoạt động', 'Bảo trì', 'Chưa gán tuyến')),
    MaTuyen VARCHAR(20) REFERENCES TUYEN_XE(MaTuyen) ON DELETE SET NULL
);

CREATE TABLE NHAN_VIEN (
    MaNhanVien VARCHAR(10) PRIMARY KEY,
    TenNhanVien VARCHAR(100) NOT NULL,
    SoDienThoai VARCHAR(15),
    ChucVu VARCHAR(50),
    MaBenXe VARCHAR(20) REFERENCES BEN_XE(MaBenXe)
);

CREATE TABLE CHUYEN_XE (
    MaChuyen VARCHAR(10) PRIMARY KEY,
    ThoiGianKhoiHanh TIMESTAMP NOT NULL,
    MaXe VARCHAR(10) REFERENCES XE_BUS(MaXe) ON DELETE CASCADE,
    MaTuyen VARCHAR(20) REFERENCES TUYEN_XE(MaTuyen),
    MaTaiXe VARCHAR(10) REFERENCES TAI_XE(MaTaiXe),
    TrangThai VARCHAR(50) DEFAULT 'Sẵn sàng' CHECK (TrangThai IN ('Sẵn sàng', 'Đang hoạt động', 'Hủy'))
);

CREATE TABLE VE (
    MaVe VARCHAR(10) PRIMARY KEY,
    GiaVe DECIMAL(12, 2) CHECK (GiaVe > 0),
    NgayDat DATE DEFAULT CURRENT_DATE,
    MaChuyen VARCHAR(10) REFERENCES CHUYEN_XE(MaChuyen),
    MaHanhKhach VARCHAR(10) REFERENCES HANH_KHACH(MaHanhKhach)
);