CREATE TABLE BEN_XE (
    MaBenXe VARCHAR(10) PRIMARY KEY,
    TenBenXe VARCHAR(100) NOT NULL,
    DiaChi TEXT
);

CREATE TABLE TAI_XE (
    MaTaiXe VARCHAR(10) PRIMARY KEY,
    TenTaiXe VARCHAR(100) NOT NULL,
    SoDienThoai VARCHAR(15),
    BangLai VARCHAR(50),
    NgaySinh DATE
);

CREATE TABLE HANH_KHACH (
    MaHanhKhach VARCHAR(10) PRIMARY KEY,
    TenHanhKhach VARCHAR(100) NOT NULL,
    SoDienThoai VARCHAR(15)
);

CREATE TABLE TUYEN_XE (
    MaTuyen VARCHAR(10) PRIMARY KEY,
    TenTuyen VARCHAR(100) NOT NULL,
    DiemDau VARCHAR(100),
    DiemCuoi VARCHAR(100),
    GiaVe DECIMAL(12, 2),
    MaBenXe VARCHAR(10) REFERENCES BEN_XE(MaBenXe)
);

CREATE TABLE XE_BUS (
    MaXe VARCHAR(10) PRIMARY KEY,
    BienSo VARCHAR(20) UNIQUE NOT NULL,
    SoCho INTEGER CHECK (SoCho > 0),
    TrangThai VARCHAR(50),
    MaTuyen VARCHAR(10) REFERENCES TUYEN_XE(MaTuyen)
);

CREATE TABLE NHAN_VIEN (
    MaNhanVien VARCHAR(10) PRIMARY KEY,
    TenNhanVien VARCHAR(100) NOT NULL,
    SoDienThoai VARCHAR(15),
    ChucVu VARCHAR(50),
    MaBenXe VARCHAR(10) REFERENCES BEN_XE(MaBenXe)
);

CREATE TABLE CHUYEN_XE (
    MaChuyen VARCHAR(10) PRIMARY KEY,
    NgayKhoiHanh DATE NOT NULL,
    GioKhoiHanh TIME NOT NULL,
    MaXe VARCHAR(10) REFERENCES XE_BUS(MaXe),
    MaTaiXe VARCHAR(10) REFERENCES TAI_XE(MaTaiXe),
    TrangThai VARCHAR(50)
);

CREATE TABLE VE (
    MaVe VARCHAR(10) PRIMARY KEY,
    SoGhe INTEGER NOT NULL,
    GiaVe_ThucTe DECIMAL(12, 2),
    NgayDat DATE DEFAULT CURRENT_DATE,
    MaChuyen VARCHAR(10) REFERENCES CHUYEN_XE(MaChuyen),
    MaHanhKhach VARCHAR(10) REFERENCES HANH_KHACH(MaHanhKhach),
    MaNhanVien VARCHAR(10) REFERENCES NHAN_VIEN(MaNhanVien)
);